import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { NavLink, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { Activity, AlertTriangle, ArrowLeft, Boxes, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, FileCheck2, GitBranch, History, LayoutList, Menu, PackageCheck, RotateCcw, ShieldCheck, X, XCircle } from 'lucide-react'
import { api, setDemoUser } from './lib/api'
import type { Approval, CaseSummary, Finding, Impact } from './types'

const labels:Record<string,string>={RECEIVED:'Received',INGESTED:'Ingested',EXTRACTION_COMPLETE:'Extracted',VALIDATION_IN_PROGRESS:'Validating',VALIDATION_FAILED:'Validation blocked',REVIEW_REQUIRED:'Review required',READY_FOR_APPROVAL:'Ready for approval',APPROVAL_PENDING:'Approval pending',APPROVED:'Approved',REJECTED:'Rejected',CHANGES_REQUESTED:'Changes requested',POSTING_IN_PROGRESS:'Posting',POSTED:'Posted',REVALIDATION_IN_PROGRESS:'Revalidating',CLOSED:'Closed',ESCALATED:'Escalated',ROLLED_BACK:'Rolled back'}
const tone=(value:string)=>value.includes('HARD')||value.includes('FAILED')||value==='ESCALATED'?'danger':value.includes('PENDING')||value.includes('REVIEW')||value==='WARNING'?'warn':value==='CLOSED'||value==='APPROVED'||value==='POSTED'?'success':'neutral'
function Badge({value}:{value:string}){return <span className={`badge ${tone(value)}`}>{labels[value]??value.replaceAll('_',' ')}</span>}
function Loading(){return <div className="state"><Activity className="spin"/> Loading governed workflow…</div>}
function ErrorState({error}:{error:Error}){return <div className="state error"><AlertTriangle/> {error.message}</div>}

const nav=[['/queue','Release queue',LayoutList],['/approvals','Approval center',ClipboardCheck],['/guide','Demo guide',FileCheck2]] as const
function Shell(){const [open,setOpen]=useState(false);const {data:users}=useQuery({queryKey:['users'],queryFn:api.users});return <div className="app-shell">
  <aside className={open?'open':''}><div className="brand"><div className="brand-mark"><GitBranch/></div><div><strong>ReleaseFlow</strong><span>Northstar Industrial Systems</span></div><button className="mobile-close" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div>
  <nav aria-label="Primary navigation">{nav.map(([href,label,Icon])=><NavLink key={href} to={href} onClick={()=>setOpen(false)}><Icon/>{label}</NavLink>)}</nav>
  <div className="governance"><ShieldCheck/><div><strong>Governed demo</strong><span>Deterministic mode · human approval required</span></div></div></aside>
  <main><header><button className="menu" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><div><span className="eyebrow">OPERATIONS CONTROL</span><h1>Engineering release command center</h1></div><label className="actor">Acting as<select defaultValue="user-coordinator" onChange={e=>{setDemoUser(e.target.value);location.reload()}}>{users?.map(u=><option value={u.id} key={u.id}>{u.name} · {u.role}</option>)}</select></label></header><Routes><Route path="/queue" element={<Queue/>}/><Route path="/cases/:id" element={<Workspace/>}/><Route path="/cases/:id/audit" element={<Audit/>}/><Route path="/approvals" element={<Approvals/>}/><Route path="/guide" element={<Guide/>}/><Route path="*" element={<Navigate to="/queue" replace/>}/></Routes></main></div>}

function Queue(){const [state,setState]=useState('');const [severity,setSeverity]=useState('');const query=useMemo(()=>{const p=new URLSearchParams();if(state)p.set('state',state);if(severity)p.set('severity',severity);const s=p.toString();return s?`?${s}`:''},[state,severity]);const {data,error,isLoading}=useQuery({queryKey:['cases',query],queryFn:()=>api.cases(query)});const {data:kpis}=useQuery({queryKey:['kpis'],queryFn:api.kpis});return <section className="page">
  <div className="page-head"><div><span className="eyebrow">RELEASE QUEUE</span><h2>Cases requiring operational control</h2><p>Evidence-backed releases moving through validation, approval, and posting.</p></div><div className="primary-metric"><Clock3/><div><span>Median packet → ERP-ready</span><strong>{String(kpis?.median_release_cycle_hours??'—')} hours</strong></div></div></div>
  <div className="toolbar"><label>Status<select value={state} onChange={e=>setState(e.target.value)}><option value="">All states</option><option value="APPROVAL_PENDING">Approval pending</option><option value="REVIEW_REQUIRED">Review required</option><option value="VALIDATION_FAILED">Validation blocked</option><option value="ESCALATED">Escalated</option></select></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severities</option><option value="HARD_STOP">Hard stop</option><option value="ERROR">Error</option><option value="WARNING">Warning</option></select></label><span className="result-count">{data?.total??0} release cases</span></div>
  {isLoading?<Loading/>:error?<ErrorState error={error}/>:<div className="case-list">{data?.items.map(c=><CaseRow key={c.id} item={c}/>)}</div>}
  </section>}
function CaseRow({item}:{item:CaseSummary}){return <NavLink to={`/cases/${item.id}`} className="case-row"><div className={`severity-rail ${tone(item.severity)}`}/><div className="case-id"><span>{item.id}</span><small>{item.release_type}</small></div><div className="case-product"><strong>{item.product}</strong><span>{item.finding_count} findings · Owner {item.owner_id?.replace('user-','')??'Unassigned'}</span></div><Badge value={item.severity}/><Badge value={item.state}/><div className="age"><Clock3/> {Math.max(1,Math.floor((Date.now()-new Date(item.created_at).getTime())/3600000))}h</div><ChevronRight/></NavLink>}

function Workspace(){const {id=''}=useParams();const {data,error,isLoading}=useQuery({queryKey:['case',id],queryFn:()=>api.case(id)});if(isLoading)return <section className="page"><Loading/></section>;if(error)return <section className="page"><ErrorState error={error}/></section>;if(!data)return null;return <section className="page"><NavLink className="back" to="/queue"><ArrowLeft/> Release queue</NavLink>
  <div className="case-title"><div><span className="eyebrow">{data.case.id} · {data.case.release_type}</span><h2>{data.case.product}</h2><p>Case version {data.case.version} · {data.documents.length} source documents · deterministic extraction</p></div><div className="title-badges"><Badge value={data.case.severity}/><Badge value={data.case.state}/></div></div>
  <div className="workflow-strip"><WorkflowStep label="Evidence" state="done"/><WorkflowStep label="Extract" state="done"/><WorkflowStep label="Validate" state={data.case.state==='VALIDATION_FAILED'?'blocked':'done'}/><WorkflowStep label="Impact" state="done"/><WorkflowStep label="Approve" state={data.case.state==='APPROVAL_PENDING'?'active':'blocked'}/><WorkflowStep label="Post & revalidate" state="future"/></div>
  <div className="workspace-grid"><div className="stack"><Panel title="Source evidence" icon={<FileCheck2/>} count={data.documents.length}>{data.documents.map((d,i)=><div className="document" key={i}><div className="file-icon">{String(d.source_type).slice(0,3)}</div><div><strong>{String(d.filename)}</strong><span>SHA-256 verified · Synthetic demonstration record</span></div><button>View evidence</button></div>)}</Panel>
  <Panel title="Validation findings" icon={<AlertTriangle/>} count={data.findings.length}>{data.findings.map(f=><FindingRow key={f.id} finding={f}/>)}</Panel></div>
  <div className="stack"><Panel title="Downstream impact" icon={<GitBranch/>} count={data.impacts.length}>{data.impacts.map(i=><ImpactRow key={i.id} impact={i}/>)}</Panel>
  {data.duplicates.length>0&&<Panel title="Ambiguous duplicate candidates" icon={<Boxes/>} count={data.duplicates.length}><div className="hard-stop-note"><XCircle/><div><strong>Automatic merge refused</strong><span>Two plausible records require a human master-data decision.</span></div></div>{data.duplicates.map((d,i)=><div className="candidate" key={i}><strong>{String(d.candidate_item_id)}</strong><span>{Math.round(Number(d.score)*100)}% agreement</span><p>{(d.reasons as string[]).join(' · ')}</p></div>)}</Panel>}
  <Panel title="Staged change set" icon={<PackageCheck/>} count={data.changes.length}>{data.changes.map((c,i)=><div className="diff" key={i}><span>{String(c.entity_type)} · {String(c.field_name)}</span><div><del>{String(c.before_value??'Unknown')}</del><ChevronRight/><ins>{String(c.after_value)}</ins></div><small>{String(c.action_class)} · approval required</small></div>)}{data.case.state==='APPROVAL_PENDING'&&<NavLink className="button primary" to="/approvals">Review approval package <ChevronRight/></NavLink>}</Panel></div></div>
  {data.postings.length>0&&<Panel title="Posting & revalidation" icon={<CheckCircle2/>} count={data.postings.length}>{data.postings.map((p,i)=><article className="posting" key={i}><div className="posting-status"><div><span className="eyebrow">TRANSACTION {String(p.id).slice(0,8)}</span><strong>{String(p.status)} · {String(p.records_written)} record written</strong></div><Badge value={data.case.state}/></div><dl><div><dt>Idempotency key</dt><dd>{String(p.idempotency_key)}</dd></div><div><dt>Before snapshot</dt><dd>{JSON.stringify(p.before_snapshot)}</dd></div><div><dt>After snapshot</dt><dd>{JSON.stringify(p.after_snapshot)}</dd></div><div><dt>Revalidation</dt><dd>No hard stops remain · case closed</dd></div></dl></article>)}</Panel>}
  <NavLink className="audit-link" to={`/cases/${id}/audit`}><History/> Inspect complete audit timeline <ChevronRight/></NavLink></section>}
function WorkflowStep({label,state}:{label:string;state:string}){return <div className={`workflow-step ${state}`}><span>{state==='done'?<CheckCircle2/>:state==='blocked'?<XCircle/>:<span/>}</span><small>{label}</small></div>}
function Panel({title,icon,count,children}:{title:string;icon:React.ReactNode;count:number;children:React.ReactNode}){return <section className="panel"><div className="panel-title"><div>{icon}<h3>{title}</h3></div><span>{count}</span></div>{children}</section>}
function FindingRow({finding}:{finding:Finding}){return <article className="finding"><div className={`finding-icon ${tone(finding.severity)}`}><AlertTriangle/></div><div><div className="finding-title"><strong>{finding.rule_id}</strong><Badge value={finding.severity}/></div><p>{finding.explanation}</p><div className="value-diff"><span>Current: <b>{String(finding.current_value)}</b></span><span>Candidate: <b>{String(finding.candidate_value)}</b></span></div><small>Evidence: {finding.evidence.document} · {finding.evidence.location} · {Math.round(finding.confidence*100)}% confidence</small></div></article>}
function ImpactRow({impact}:{impact:Impact}){return <article className="impact"><div className="impact-type">{impact.impact_type.replaceAll('_',' ')}</div><div><strong>{impact.record_id}</strong><p>{impact.summary}</p><small>Path: {impact.graph_path.join(' → ')}</small></div><Badge value={impact.risk}/></article>}

function Approvals(){const qc=useQueryClient();const {data,error,isLoading}=useQuery({queryKey:['approvals'],queryFn:api.approvals});const [active,setActive]=useState<Approval|null>(null);const [rationale,setRationale]=useState('');const [decision,setDecision]=useState('APPROVED');const mutation=useMutation({mutationFn:()=>api.decide(active!.id,decision,rationale),onSuccess:()=>{setActive(null);setRationale('');qc.invalidateQueries({queryKey:['approvals']})}});return <section className="page"><div className="page-head"><div><span className="eyebrow">APPROVAL CENTER</span><h2>Consequential changes awaiting judgment</h2><p>Every decision is role-checked, version-bound, and preserved in the audit trail.</p></div></div>{isLoading?<Loading/>:error?<ErrorState error={error}/>:<div className="approval-grid">{data?.map(a=><article className="approval-card" key={a.id}><div className="approval-top"><div className="risk-orb"><ShieldCheck/></div><div><span>{a.id}</span><h3>{a.case_id} change package</h3></div><Badge value={a.status}/></div><dl><div><dt>Required role</dt><dd>{a.required_role}</dd></div><div><dt>Bound version</dt><dd>Case v{a.case_version}</dd></div><div><dt>Control</dt><dd>Token invalidates on any case change</dd></div></dl><button className="button primary" disabled={a.status!=='PENDING'} onClick={()=>setActive(a)}>Inspect and decide <ChevronRight/></button></article>)}</div>}
  {active&&<div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="decision-title"><button className="modal-close" onClick={()=>setActive(null)} aria-label="Close"><X/></button><span className="eyebrow">HUMAN CONTROL GATE</span><h2 id="decision-title">Decision for {active.case_id}</h2><p>Approval authorizes only the exact, versioned staged changes. It does not authorize substitutions, scrap, cancellation, or automatic merges.</p><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="APPROVED">Approve exact change set</option><option value="REJECTED">Reject</option><option value="CHANGES_REQUESTED">Request changes</option></select></label><label>Rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Required for this governed decision" rows={4}/></label>{mutation.error&&<p className="form-error">{mutation.error.message}</p>}<button className="button primary" disabled={!rationale.trim()||mutation.isPending} onClick={()=>mutation.mutate()}>{mutation.isPending?'Recording decision…':'Submit governed decision'}</button></div></div>}
  </section>}

function Audit(){const {id=''}=useParams();const {data,error,isLoading}=useQuery({queryKey:['audit',id],queryFn:()=>api.audit(id)});return <section className="page"><NavLink className="back" to={`/cases/${id}`}><ArrowLeft/> Case workspace</NavLink><div className="page-head"><div><span className="eyebrow">IMMUTABLE AUDIT</span><h2>{id} event timeline</h2><p>Human and machine actions with state, actor, service, and correlation evidence.</p></div></div>{isLoading?<Loading/>:error?<ErrorState error={error}/>:<div className="timeline">{data?.map((e,i)=><article key={String(e.id)}><div className="timeline-dot">{i+1}</div><div><div className="event-head"><strong>{String(e.action).replaceAll('_',' ')}</strong><Badge value={String(e.result)}/></div><p>{String(e.service)} · {String(e.actor_type)} {String(e.actor_id)}</p><span>{String(e.previous_state??'Created')} → {String(e.new_state??'Recorded')}</span><small>Correlation {String(e.correlation_id)}</small></div></article>)}</div>}</section>}

const guides=[['new-pump','01','New pump assembly','Resolve missing UOM, BOM quantity conflict, duplicate risk, and vendor approval before release.'],['package-change','02','Supplier package-size change','Propagate pack 20→24 and MOQ 100→120 while exposing nonconforming open POs.'],['obsolete-revision','03','Obsolete component revision','Trace the old seal through BOMs, inventory, purchasing, WIP, and customer commitments.'],['circular-bom','04','Circular BOM hard stop','See structural graph validation prevent approval and posting.'],['ambiguous-duplicate','05','Ambiguous duplicate','Compare two plausible items and observe the system refuse an unsafe automatic merge.']]
function Guide(){const nav=useNavigate();const qc=useQueryClient();const replay=useMutation({mutationFn:(key:string)=>api.replay(key),onSuccess:r=>{qc.clear();nav(`/cases/${r.case_id}`)}});return <section className="page"><div className="page-head"><div><span className="eyebrow">GUIDED DEMONSTRATION</span><h2>Five releases. One governed operating loop.</h2><p>Each scenario resets to a deterministic evidence packet and reproducible outcome.</p></div></div><div className="guide-grid">{guides.map(([key,n,title,copy])=><article key={key}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p><button className="button" onClick={()=>replay.mutate(key)}><RotateCcw/> Replay case</button></div></article>)}</div><div className="refusal"><ShieldCheck/><div><span className="eyebrow">WHAT RELEASEFLOW REFUSES TO AUTOMATE</span><h3>No silent merges. No unsafe substitutions. No consequential writes without approval.</h3><p>Deterministic rules remain authoritative. Model-generated fields are evidence-linked candidates, never release decisions.</p></div></div></section>}
export default Shell
