from enum import StrEnum


class CaseState(StrEnum):
    RECEIVED = "RECEIVED"
    INGESTED = "INGESTED"
    EXTRACTION_COMPLETE = "EXTRACTION_COMPLETE"
    VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    POSTING_IN_PROGRESS = "POSTING_IN_PROGRESS"
    POSTED = "POSTED"
    REVALIDATION_IN_PROGRESS = "REVALIDATION_IN_PROGRESS"
    CLOSED = "CLOSED"
    ESCALATED = "ESCALATED"
    ROLLED_BACK = "ROLLED_BACK"


class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    HARD_STOP = "HARD_STOP"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class Role(StrEnum):
    COORDINATOR = "Engineering Change Coordinator"
    MASTER_DATA = "Master Data Analyst"
    PLANNER = "Supply Planner"
    PROCUREMENT = "Procurement Analyst"
    MANUFACTURING = "Manufacturing Engineer"
    APPROVER = "Approver"
    ADMIN = "Administrator"
    AUDITOR = "Auditor"
